[2024-11-03T03:23:08.685+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-03T03:23:08.706+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: load_sales_data_to_db.store_sales_data_raw scheduled__2024-11-03T03:21:00+00:00 [queued]>
[2024-11-03T03:23:08.724+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: load_sales_data_to_db.store_sales_data_raw scheduled__2024-11-03T03:21:00+00:00 [queued]>
[2024-11-03T03:23:08.725+0000] {taskinstance.py:2865} INFO - Starting attempt 2 of 2
[2024-11-03T03:23:08.749+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): store_sales_data_raw> on 2024-11-03 03:21:00+00:00
[2024-11-03T03:23:08.753+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=164) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-11-03T03:23:08.754+0000] {standard_task_runner.py:72} INFO - Started process 181 to run task
[2024-11-03T03:23:08.759+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'load_sales_data_to_db', 'store_sales_data_raw', 'scheduled__2024-11-03T03:21:00+00:00', '--job-id', '17', '--raw', '--subdir', 'DAGS_FOLDER/dags/raw/dag_load_sales_data_to_db.py', '--cfg-path', '/tmp/tmp9zz4o0gf']
[2024-11-03T03:23:08.759+0000] {standard_task_runner.py:105} INFO - Job 17: Subtask store_sales_data_raw
[2024-11-03T03:23:08.795+0000] {task_command.py:467} INFO - Running <TaskInstance: load_sales_data_to_db.store_sales_data_raw scheduled__2024-11-03T03:21:00+00:00 [running]> on host 6c96a25de617
[2024-11-03T03:23:08.938+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='load_sales_data_to_db' AIRFLOW_CTX_TASK_ID='store_sales_data_raw' AIRFLOW_CTX_EXECUTION_DATE='2024-11-03T03:21:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-11-03T03:21:00+00:00'
[2024-11-03T03:23:08.940+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-11-03T03:23:08.941+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-11-03T03:23:08.941+0000] {logging_mixin.py:190} INFO - Current task name:store_sales_data_raw state:running start_date:2024-11-03 03:23:08.707386+00:00
[2024-11-03T03:23:08.942+0000] {logging_mixin.py:190} INFO - Dag name:load_sales_data_to_db and current dag run status:running
[2024-11-03T03:23:08.942+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-03T03:23:08.999+0000] {raw_store_sales_data.py:52} ERROR - Failed to insert data into DuckDB: Catalog Error: Table with name sales does not exist!
Did you mean "temp.information_schema.tables"?
[2024-11-03T03:23:09.011+0000] {raw_store_sales_data.py:56} INFO - Closed DuckDB connection.
[2024-11-03T03:23:09.012+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/logic/raw_store_sales_data.py", line 27, in store_sales_data_to_db
    conn.execute("""
duckdb.duckdb.CatalogException: Catalog Error: Table with name sales does not exist!
Did you mean "temp.information_schema.tables"?
[2024-11-03T03:23:09.030+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-11-03T03:23:09.031+0000] {logging_mixin.py:190} INFO - Task start:2024-11-03 03:23:08.707386+00:00 end:2024-11-03 03:23:09.029820+00:00 duration:0.322434
[2024-11-03T03:23:09.031+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): store_sales_data_raw> dag:<DAG: load_sales_data_to_db> dagrun:<DagRun load_sales_data_to_db @ 2024-11-03 03:21:00+00:00: scheduled__2024-11-03T03:21:00+00:00, state:running, queued_at: 2024-11-03 03:22:56.369695+00:00. externally triggered: False>
[2024-11-03T03:23:09.032+0000] {logging_mixin.py:190} INFO - Failure caused by Catalog Error: Table with name sales does not exist!
Did you mean "temp.information_schema.tables"?
[2024-11-03T03:23:09.033+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=load_sales_data_to_db, task_id=store_sales_data_raw, run_id=scheduled__2024-11-03T03:21:00+00:00, execution_date=20241103T032100, start_date=20241103T032308, end_date=20241103T032309
[2024-11-03T03:23:09.048+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-03T03:23:09.048+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 17 for task store_sales_data_raw (Catalog Error: Table with name sales does not exist!
Did you mean "temp.information_schema.tables"?; 181)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/logic/raw_store_sales_data.py", line 27, in store_sales_data_to_db
    conn.execute("""
duckdb.duckdb.CatalogException: Catalog Error: Table with name sales does not exist!
Did you mean "temp.information_schema.tables"?
[2024-11-03T03:23:09.071+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-11-03T03:23:09.081+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-03T03:23:09.082+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
